name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build program
        run: yarn build

      - name: Build Documentation Pages
        run: yarn build:docs

      - name: Publish
        uses: actions/deploy-pages@v3.0.1
        with:
          artifact_name: "dist/docs"
