name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:  
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build program
        run: yarn build

      - name: Build Documentation Pages
        run: yarn build:docs

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/docs